name: Deploy Next.js App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Ajouter la clé SSH privée et configurer SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 98.81.60.249 >> ~/.ssh/known_hosts  # Remplacer par ton IP

      - name: Vérifier la connexion SSH
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@98.81.60.249 "echo 'Connexion SSH réussie'"

      - name: mettre a jour le code avec git pull
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.81.60.249 "cd /home/ubuntu/ToDoList-CI-CD && git pull"


      - name: netoyer  les anciens  dependances
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.81.60.249 "cd /home/ubuntu/ToDoList-CI-CD && rm -rf node_modules package-lock.json"


      - name: installer les dependances
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.81.60.249 "cd /home/ubuntu/ToDoList-CI-CD && npm install"

      - name: build du projet
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.81.60.249 "cd /home/ubuntu/ToDoList-CI-CD && npm run build"

      - name: demarrer l'application avec PM2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@98.81.60.249 "cd /home/ubuntu/ToDoList-CI-CD && pm2 start npm --name 'nextjs-app' -- run start"
 

